networks:
  expense: {}
volumes:
  mysql:
services:
  backend:
    image: backend:1.0.0
    networks:
    - expense
    container_name: backend
    depends_on:
    - mysql

#docker run -d --name mysql --network expense -v mysql:/var/lib/mysql mysql:1.0.0
  mysql:
    image: mysql:1.0.0
    networks:
    - expense
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
    
  Frontend:
    image: frontend
    networks:
    - expense
    container_name: frontend:1.0.0
    ports:
    - 80:80
    depends_on:
    - backend
